### ISSUE TITLE
请教问题

### ISSUE THREAD

**Issue by Bhongcheng** [smduan/Fed-CCVR#1]
我在执行代码时，发现g_cov[0]的值都为nan，在生成虚拟表征vr的时候报错退出，请问这是为什么啊。。。

**Comment by Bhongcheng** [comment]
![image](https://user-images.githubusercontent.com/90205287/207561599-dabf39e2-5349-40eb-bc19-e8948026969c.png)
![image](https://user-images.githubusercontent.com/90205287/207561643-403a3305-920c-4f6a-9150-72f48f7a00ea.png)

**Comment by Bhongcheng** [comment]
但是我再次运行代码，加载先前训练的模型，注释掉联邦训练部分，程序顺利跑通，没有出现先前的问题

**Comment by Bhongcheng** [comment]
反复运行后，发现有时候还是会出现这种问题。。。

**Comment by smduan** [comment]
不好意思，因为这个算法效果并不好，我们也早已不再维护

**Comment by Bhongcheng** [comment]
谢谢你的回复。能否请问一下为什么说效果并不好呀？我运行你的代码示例，确实是有提升的呀……

**Comment by smduan** [comment]
> 

因为我们最后没有复现论文中的结果。这篇论文的一个重要贡献是发现Non-IID数据对模型影响最大的是模型最后的分类层，因此提出使用虚拟特征数据来调试模型分类层。但是有一个问题，这个虚拟特征是使用高斯混合模型提取网络最后一层特征的混合高斯分布，然后使用学习到的全局高斯混合分布生成的。这个方法比较依赖初始模型的鲁棒性，如果初始模型训练的不够好，高斯混合模型学习到的分布可能是错的，后面使用生成的虚拟特征调试模型就没效果了。如果感兴趣的话你可以在这个话题下进一步探索怎么更好地生成虚拟特征或者怎么调试模型分类层。
